### ISSUE TITLE
Lange functies

### ISSUE THREAD

**Issue by Qvdpost** [danivenk/UVA_Minor-Programming_Programming-Theory#8]
Astar (en andere algoritmes) heeft een ontzettend lange functie 'create_line'. Kijk of je daar losse functionaliteiten kunt identificeren die eventueel een losse methode zouden kunnen zijn. 
Dat zou ontzettend helpen om de code te lezen en begrijpen.

**Comment by MichaelF89** [comment]
create_line methodes zijn opgedeeld in kleinere methodes
